[project]
name = "web-ban-hang-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "quyennv1912ptit", email = "quyennv19122006@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "einops>=0.8.2",
    "fastapi-pagination>=0.16.0",
    "fastapi[standard]>=0.141.1",
    "firebase-admin>=7.7.0",
    "numpy>=2.5.3",
    "pgvector>=0.5.0",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.13",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "sentence-transformers<6.1.0",
    "sqlmodel>=0.0.47",
    "timm>=1.0.30",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
    "transformers<5",
]

[project.scripts]
web-ban-hang-backend = "web_ban_hang_backend:main"

[tool.fastapi]
entrypoint = "web_ban_hang_backend.main:app"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
